### ISSUE TITLE
Please support Windows

### ISSUE THREAD

**Issue by CamiloMM** [codeclimate/javascript-test-reporter#14]
I'm working on a node binding of [Avisynth](http://avisynth.nl/) (which is Windows-only). I'm running the tests on AppVeyor, which is like Travis CI but with Windows instead of Ubuntu. Therefore, I need to upload code coverage from node running on Windows.

I've had an email exchange with Jonathan from your team about this but it's been a few weeks so maybe it has stuck in a spam filter ([here's a copy](http://fiddle.jshell.net/78kerfzr/show/)).

At any rate, I have put up [a pull request](https://github.com/codeclimate/javascript-test-reporter/pull/13) that contains simple fixes that address the problem. Just merging that will add Windows support to `codeclimate-test-reporter`, and it's small, easy-to-review code, so I'd appreciate if you guys could take a look at it.

Happy New Year and hope you're not too overworked. Your service is pretty good :)

**Comment by jonathancadepowers** [comment]
Thanks again for the PR on this. Sorry that it's taking us awhile to review and merge, but this is still on our list.
