### ISSUE TITLE
Provide grunt task interface to reporter

### ISSUE THREAD

**Issue by willscott** [codeclimate/javascript-test-reporter#2]
It would be great to allow the test reporter to be called as a grunt task (gruntjs.com)

This would take the form of an additional entry point to reporting in a 'tasks' folder.

**Comment by avdg** [comment]
This repo still needs a library, or we end up using grunt plugins using the command line.

Though I'm watching https://github.com/MrBoolean/grunt-codeclimate very closely (unstable code for now!). Just waiting for a library so things are easy to integrate.

**Comment by dblandin** [comment]
Hey @willscott,

Unfortunately we're unable to action this work right now. https://github.com/MrBoolean/grunt-codeclimate looks like a good workaround for the time being.
