### ISSUE TITLE
Maybe keep support for codeclimate binary

### ISSUE THREAD

**Issue by benedictfischer09** [codeclimate/javascript-test-reporter#22]
According to the 0.0.4 docs it made sense to run commands like below on your CI platform to post to code climate

- npm install -g codeclimate-test-reporter
- CODECLIMATE_REPO_TOKEN=token codeclimate < coverage/lcov.info

Since its always a fresh global install it gets the newest release, now that the binary is called  codeclimate-test-reporter instead of codeclimate this throws an error. Minor change to fix it in the app, but might make sense to just alais codeclimate to codeclimate-test-reporter so it doesn't break people's coverage deployment

**Comment by sushantdhiman** [comment]
+1, Having same issue in `sequelize` project. Test coverage just stopped working. Checked logs to see `codeclimate` command not found error. You should keep alias `codeclimate` to prevent such breaks.

**Comment by GordonDiggs** [comment]
Apologies for the inconvenience here. The `codeclimate` binary is now in use by our [CLI](https://github.com/codeclimate/codeclimate), and in order to prevent collisions, we had to rename the reporter here. My suggestion would be to update the test reporter and use the new binary if possible.
