### ISSUE TITLE
Make usable as library

### ISSUE THREAD

**Issue by Xiphe** [codeclimate/javascript-test-reporter#26]
the [npm main entry](https://github.com/codeclimate/javascript-test-reporter/blob/master/package.json#L5) point to a non-existing file.

It would be great to use this tool from inside node without having to spawn a child process.
(like in gulp, [grunt](https://github.com/MrBoolean/grunt-codeclimate-reporter), npm scripts)

@avdg did a great job on making this possible with #19 (which is now closed without merge)

please consider making this possible.

**Comment by pbrisbin** [comment]
I @Xiphe I think that'd be great too. Unfortunately we don't have the ability to action that work right now, and I don't think I have to context to correctly resurrect #19. I've added the help-wanted label here and maybe someone will be able to take this work on sooner than we'd be able to get to it.

**Comment by dblandin** [comment]
Hey @Xiphe,

We've started work on a new unified test reporter: https://github.com/codeclimate/test-reporter

That reporter is written in go and compiles as an executable binary. We're unlikely to provide language-specific libraries moving forward. Plugins for gulp, grunt, etc would probably want to wrap the binary execution.

I'm going to close this issue for now but thanks for your input!

**Comment by Xiphe** [comment]
Sweet! Thanks for the update
