### ISSUE TITLE
Coverage for branches/prs

### ISSUE THREAD

**Issue by gdborton** [codeclimate/javascript-test-reporter#35]
I couldn't find a feature request section for codeclimate.com, please let me know if there is a better place for this.

As part of my CI toolset, I enforce incremental test coverage of existing files in my repository.  If a file's coverage decreases I fail a build.  Currently the fastest way for contributors to get feedback on what is uncovered is for them to download Istanbul's coverage report (6mb) as an archive.  I'd love to be able to link them directly to a codeclimate coverage page for their branch/pr.

Is this something that's being thought about or on the road map?

**Comment by wfleming** [comment]
Thanks for the feedback @gdborton. Right now, our test coverage integration is limited to a repository's main branch. We're planning improvements to our test coverage integration overall right now, so while I can't give a concrete answer on when this is a use case we might be able to support, this is definitely a good idea we'll take into account while we plan that work.

**Comment by dblandin** [comment]
Hey @gdborton,

Some good news: We now accept and process test coverage reports for non-default branches.

We don't yet have an interface to view test coverage for non-default branches on codeclimate.com but you can view annotations inline on GitHub when viewing files or PRs using our new super cool [Chrome extension](https://codeclimate.com/browser-extension).

If you're already using our test reporters, this should JustWork™. Let us know if you run into any issues.
