### ISSUE TITLE
add explicit instructions about how to use with Go

### ISSUE THREAD

**Issue by afeld** [codeclimate/javascript-test-reporter#36]
I think I can figure it out, but would be helpful for others to include more explicit instructions ("run this, then this") in the README. Might also need a caveat for running over multiple packages, a la

https://github.com/codecov/example-go#caveat-multiple-files

Thanks!

**Comment by afeld** [comment]
Would also be useful to mention this in [the docs](https://docs.codeclimate.com/docs/setting-up-test-coverage), since I was searching around for "code climate golang test cover" and couldn't find anything.

**Comment by afeld** [comment]
@mrb Bump!

**Comment by mrb** [comment]
@afeld D'oh! Thanks for the bump

**Comment by mrb** [comment]
@afeld Are these instructions sufficient? https://github.com/codeclimate/javascript-test-reporter#installation

**Comment by afeld** [comment]
Hmm, appears there isn't a straightforward way to generate a coverage file for multiple files (https://github.com/golang/go/issues/6909), so I would add a note/link about that. Also, as mentioned above, there isn't any mention of Go in https://docs.codeclimate.com/docs/setting-up-test-coverage, and looking in the `javascript-test-reporter` for Go support isn't the most obvious thing.

**Comment by mrb** [comment]
@afeld Understood. We're working out internally how to handle this kind of thing and want to make some major improvements to coverage in general, so I suspect that has been the blocker here for investing in documentation. I'll ping you in Slack to chat more.

**Comment by dblandin** [comment]
Hey @afeld,

Thank for the issue!

As we're winding down development on this reporter, I'd recommend checking out our new test reporter (which has first-class support for go test coverage report formats) and migrating to it if you're interested!

https://github.com/codeclimate/test-reporter
https://codeclimate.com/changelog/591c99570d51f6481f001291

It's decoupled from the coverage tool used to generate the report, distributed as a static binary, and has support for parallelized builds. 🎉
