### ISSUE TITLE
usage in CI environments without `.git` subdirectory

### ISSUE THREAD

**Issue by jeffreywescott** [codeclimate/javascript-test-reporter#44]
We are trying to integrate codeclimate test coverage, and are using Codeship as our CI system, in particular their Docker-based CI system. Our project is a JS project, and we've installed the `codeclimate-test-reporter` npm module to upload our `lcov` report.

The _problem_ is that that utility expects to be working with a checked-out `git` repository, but in the case of codeship, no `git` repository is available. As such, it cannot run the correct series of `git log` and `git branch` commands to add the git information to the JSON before sending the data to codeclimate.

Codeship _does_, however, have 2/3 pieces of this information [available via environment variables](https://codeship.com/documentation/docker/steps/).

Here's what's available:

`CI_COMMIT_ID` (for head)
`CI_BRANCH` (for branch)

There's no commit timestamp available, but there _is_ a build timestamp that could be used instead:

`CI_TIMESTAMP`

My questions are:
1. How important is the commit timestamp for coverage information? Can we fake it?
2. Would it be possible to change `codeclimate-test-reporter` in such a way as to use the aforementioned environment variables (perhaps by supporting command-line options)?

We're really anxious to get this up and running, so any suggestions you have would be amazing.

Thanks.

**Comment by bk-one** [comment]
+1

**Comment by ash14** [comment]
@jeffreywescott can you comment on whether the changes in this PR solves your issues as well?

**Comment by dblandin** [comment]
Hey @jeffreywescott ,

Thank for the issue. We're winding down development on this reporter.

I recommend checking out our new test reporter and migrating to it if you're interested!

It's decoupled from the coverage tool used to generate the report, distributed as a static binary, and has support for parallelized builds. 🎉 

https://github.com/codeclimate/test-reporter
https://codeclimate.com/changelog/591c99570d51f6481f001291

CodeShip recently wrote a blog post explaining how to setup our new test reporter for their CI environments: https://blog.codeship.com/integrating-code-climate-with-codeship/

They also have some docs available: https://documentation.codeship.com/general/integrations/codeclimate/ 

And we're of course willing to help you get setup if you run into issues. Feel free to open up an issue on the new repo.

Thanks!
