### ISSUE TITLE
Need clarification on codeclimate-test-reporter

### ISSUE THREAD

**Issue by amitrai99** [codeclimate/javascript-test-reporter#50]
Can you add more details about where the `npm install` step mentioned in your doc needs to be done. Is this supposed to be done developer's machine or other environment.

`npm install -g codeclimate-test-reporter`

**Comment by wfleming** [comment]
Hi @amitrai99,

The `codeclimate-test-reporter` package should be installed in whichever environment you plan to report coverage results from. Most users run the test reporter as part of their CI test runs, and we would recommend going that route. Does that help?

**Comment by amitrai99** [comment]
That helps. Thanks!
