### ISSUE TITLE
Update doc to include the use of travis gem to encrypt the repo_token

### ISSUE THREAD

**Issue by quimarche** [codeclimate/javascript-test-reporter#51]
Ref. https://docs.travis-ci.com/user/code-climate/

**Comment by dblandin** [comment]
Hi @quimarche,

We don't consider the Code Climate repo token secret. It is used only to submit test coverage data and can be safely committed directly into a public CI configuration file. This token is not authorized to access any data within a Code Climate account or its repositories.

We have a longer answer [here on our docs site](https://docs.codeclimate.com/v1.0/docs/test-coverage-troubleshooting-tips#section--should-i-keep-my-test-coverage-token-secret-).

You're free to encrypt the value if you wish but we don't consider it a required step.
