### ISSUE TITLE
Integrate Flow type coverage

### ISSUE THREAD

**Issue by ilionic** [codeclimate/javascript-test-reporter#53]
Sorry if it's wrong place for suggestion. Would be great if codeclimate add support for Flowtype as it's becoming as important as unit testing.
https://www.npmjs.com/package/flow-coverage-report

**Comment by maxjacobson** [comment]
Hi @ilionic -

This is a neat suggestion!

Flow coverage isn't test coverage, exactly, right?

I'm having a hard time imagining our test coverage tool bending to represent another kind of coverage at the moment.

I _definitely can_ imagine a Code Climate engine which wraps `flow-coverage-report` and creates issues for functions which don't have flow type annotations. New PRs would get a red status check if they introduce new issues, which could help you remember to follow that convention.

Does that sound useful?

**Comment by ilionic** [comment]
Sounds definitely useful!
It's not exactly test coverage but separate addition - percentage of functions covered by Flow (like in Nuclide for Atom or `flow-coverage-report`)
Another aspect is actually running flow and validating types (here process bit similar to `eslint`). 
Of course it's straightforward setup in CI, but I think it would be great addition to Code Climate code quality tools.

**Comment by maxjacobson** [comment]
Cool, that does sound useful.

I've made a note in our internal feature request tracker that we should consider making such an engine, but can't make any guarantees about when we'll be able to prioritize it.

In the meantime, if you're interested in working on it, we'd be more than happy to offer mentorship and guidance. We have [a blog post](http://blog.codeclimate.com/blog/2015/07/07/build-your-own-codeclimate-engine/) that explains the steps, and you can join our community slack by filling out [this form](https://codeclimate.com/dev_form).
