### ISSUE TITLE
go coverage does not appear

### ISSUE THREAD

**Issue by aep** [codeclimate/javascript-test-reporter#54]
not sure how to get this working.

```
CODECLIMATE_REPO_TOKEN=abc123 codeclimate-test-reporter < service.coverprofile                                                                                                                            
Sending test coverage results to codeclimate.com ...
Test coverage data sent.
```

yet nothing appears in codeclimates dashboard. it still says "Test Coverage Not Setup"

service.coverprofile    contains a whole bunch of stuff and go tool cover reads it fine

**Comment by aep** [comment]
intercepting the http request, i can see that the file names are wrong.
GOPATH is ~/workspace/
PWD is ~/workspace/src/github.com/foo/liberator

service/service.coverprofile contains:

src/github.com/foo/liberator/middleware.go

but the filename sent to codeclimate is

"workspace/src/github.com/foo/liberator/service/middleware.go"

**Comment by dblandin** [comment]
Hey @aep,

Thank for the issue. We're winding down development on this reporter.

I'd recommend checking out our new test reporter (which has first-class support for go test coverage report formats) and migrating to it if you're interested!

https://github.com/codeclimate/test-reporter
https://codeclimate.com/changelog/591c99570d51f6481f001291

It's decoupled from the coverage tool used to generate the report, distributed as a static binary, and has support for parallelized builds. 🎉
