### ISSUE TITLE
Upgrade to request@2.82.0 to fix security vulnerabilities

### ISSUE THREAD

**Issue by njh** [codeclimate/javascript-test-reporter#68]
Hello,

I received a vulnerability report from Snyk because my package.json depends upon codeclimate-test-reporter `0.5.0`.

https://snyk.io/test/npm/codeclimate-test-reporter

Apparently the fix is to upgrade the codeclimate dependency on `request` to version `2.82.0`.

nick.

**Comment by maxjacobson** [comment]
Hi Nicholas. That is worrisome. The best thing to do would be to switch over to [the language-agnostic test reporter](https://github.com/codeclimate/test-reporter), since this one is [deprecated](https://github.com/codeclimate/javascript-test-reporter#codeclimate-test-reporter---deprecated).

**Comment by njh** [comment]
Thanks Max. Sorry, I missed the big DEPRECATED banner on the homepage.

**Comment by maxjacobson** [comment]
:) no problem
