### ISSUE TITLE
Vulnerability in dependencies

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [codeclimate/javascript-test-reporter#69]
Hi,

Github reports about vulnerabilities in one of the dependencies when using `codeclimate-test-reporter`.

Please update to newer version of `request` package.

The vulnerable package is `hoek`. The dependency chain is as follows:
`request -> hawk -> cryptiles -> book -> hoek`

**Comment by eutopian** [comment]
Hi there, thanks for raising this issue. This test reporter is no longer being maintained and has been deprecated, please consider using our [current version](https://github.com/codeclimate/test-reporter)

Another note, this is the same issue as the most recently closed one [here](https://github.com/codeclimate/javascript-test-reporter/issues/68)
